services:

  # Source MariaDB container
  source_mariadb:
    image: mariadb:10.3
    container_name: source_mariadb
    restart: always
    ports:
      - "3306:3306"  # Access from host
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sourcedb
      MYSQL_USER: sourceuser
      MYSQL_PASSWORD: sourcepassword
      TZ: Asia/Jakarta
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./source_mariadb/dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Target MariaDB container
  target_mariadb:
    image: mariadb:10.3
    container_name: target_mariadb
    restart: always
    ports:
      - "3307:3306"  # Access from host
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: targetdb
      MYSQL_USER: targetuser
      MYSQL_PASSWORD: targetpassword
      TZ: Asia/Jakarta
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./target_mariadb/dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  daily-python:
    build:
      context: ./etl-cron  
    container_name: daily-python
    restart: always
    volumes:
      - ./etl-cron/script.py:/app/script.py
      - ./etl-cron/crontab:/etc/crontabs/root
